# [unstable]
# codegen-backend = true
#
# [profile.dev]
# codegen-backend = "cranelift"
#
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = [
# 	"-Clink-arg=-fuse-ld=/bin/mold",
#         "-Ctarget-cpu=native",
# 	"-Zthreads=8", 
# 	"-Ztrack-diagnostics",
# 	"-Zpanic-abort-tests"
# ]

[target.x86_64-unknown-linux-gnu]
linker = "/bin/clang"
rustflags = [
	"-Clink-arg=-fuse-ld=/bin/mold",
	"-Ctarget-cpu=native",
]


[alias]
t = "nextest run"
a = "cargo-add"
f = "fix --allow-dirty --allow-no-vcs"
fc = "clippy --fix --allow-dirty --allow-no-vcs"
