# [unstable]
# codegen-backend = true
#
# [profile.test.package.proton-mail-tui]
# codegen-backend = "cranelift"
#
# [profile.test]
# codegen-backend = "cranelift"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
	"-Clink-arg=-fuse-ld=/bin/mold",
	# "-Zthreads=8", 
	# "-Ztrack-diagnostics",
	# "-Zpanic-abort-tests"
]

[profile.dev.package."*"]
debug = "line-tables-only"

[profile.dev.build-override]
opt-level = 1

[alias]
t = "nextest run"
a = "cargo-add"
f = "fix --allow-dirty --allow-no-vcs"
fc = "clippy --fix --allow-dirty --allow-no-vcs"
