{ config, pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
# kanata
    atool
      automake
      bash
      bat
      brightnessctl      
      bun
      cacert
      cmake
      cron
      dig
      discord
      eza
      fcp
      fd
      fish
      fzf
      gcc
      git
      gnumake
      gnupg
      google-chrome
      grim
      home-manager
      htop
      hyperfine
      hyprpaper
      imagemagick
      inetutils
      jdk8
      jetbrains.rust-rover
      jq
      kitty
      libnotify
      lldb_16
      llvmPackages.bintools
      llvmPackages_17.stdenv
      lua51Packages.lua-lsp
      luajit
      luajitPackages.lua-lsp
      lutris
      mako
      massif-visualizer
      monitor
      neovim
      nil
      nmap
      nodePackages_latest.pnpm
      nodePackages_latest.typescript-language-server
      nodejs_20
      nox
      nwg-look
      oh-my-fish
      openssl
      pavucontrol
      perl
      pkg-config
      python3
      ripgrep
      rocmPackages.llvm.clang-tools-extra
      rofi-wayland
      rsync
      rustup
      scrot
      sd
      slurp
      starship
      steam
      stow
      strace
      tig
      tmux
      tokei
      unzip
      valgrind
      waybar
      wget
      wl-clipboard
      wl-screenrec
      zoxide
      fuc
      openssl.dev
      openssl
      xdg-desktop-portal-hyprland
      pipewire
      wireplumber
      atuin
      fastfetch
      wireguard-tools
      file
      slack
      zoom-us
      cryptsetup
      tor-browser
      ];
  }
